#!perl
use feature say;
no warnings all;

@c = ('$_', 0..9, qw(e / * % + - & . ^));# | ~ < > [ ]));

#for $a (grep !/^\w/, @c) {

for $a (@c) {
say $a;
for $b (@c) {
for $c (@c) {
for $d (@c) {
for $e (@c) {
	$code = "$a$b$c$d$e";
	@_ = qw(5 0 0 0 4 4 3 3 3 3 3 4 4 5 0 0 5 6 6);
	$_ = 17;
	next unless eval $code == -3;
	@_ = qw(4 0 0 6 4 4 3 3 3 3 3 4 4 0 0 0 6 6 6);
	$_ = 18;
	next unless eval $code == -11;
	say "Match found! $code";
}
}
}
}
}
#134%-$_
#chr^*0
#172%$_		-66%$_
#478%$_		$_*3&6
#7516%$_	$_*@_&6
#784%$_		@_*$_&6
#-134%$_        $_^$_+2
